config/routes.rb
Rails.application.routes.draw do
  resources :matches

  resources :likes

  resources :users

  resources :items

  root 'items#index'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/match.rb
class Match < ActiveRecord::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:first_item_id, :second_item_id)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_item_id %><br>
    <%= f.number_field :first_item_id %>
  </div>
  <div class="field">
    <%= f.label :second_item_id %><br>
    <%= f.number_field :second_item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<header class="header-cont">
			<div class="row">
			<div class="col-xs-12">
				<%=image_tag("Troker_orange.png", alt: "Logo")%>
			</div>
		</div>
</header>
<div class="profil" style="margin-top:70px">
	<div class="fond" style="opacity:0.3;">
		<%=image_tag("profil.jpg", alt: "profil")%>
	</div>
	<div class="img-round" style="margin-top:-120px;height:120px">
		<%=image_tag("profil.png", alt: "profil 2")%>
		<p class="h4">Jeanne C.</p>
		<p class="h5">Bordeaux - Guingamp</p>
	</div>
</div>
<div class="col-md-12">
	<div class="row">
			<div class="row section padding">
				<div class="col-xs-6">
					<div class="title">
						<h1 class="h5" style="text-transform:uppercase;color:#ff8b00">Matches</h1>
					</div>
				</div>
				<div class="col-xs-6"style="height:35px">
				<p class="h6" style="margin-top: 10px;font-weight: bold;"><%= link_to 'New Match', new_match_path %></p>
				</div>
			</div>


    <% @matches.each do |match| %>
	<div class="row section padding-bottom">
		<div class="col-xs-5">
			<div class="rond" style="float:right"></div>
			<p><%= match.first_item_id %></p>
		</div>
		<div class="col-xs-2">
			<span class="icon-arrows"></span>
		</div>
		<div class="col-xs-5">
			<div class="rond" style="float:right"></div>
			<p><%= match.second_item_id %></p>
		</div>
	</div>
     
        <%= link_to 'Show', match %>
        <%= link_to 'Edit', edit_match_path(match) %>
        <%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %>
      
    <% end %>
	
	</div>
</div>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First item:</strong>
  <%= @match.first_item_id %>
</p>

<p>
  <strong>Second item:</strong>
  <%= @match.second_item_id %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>